# Generated by Django 4.2.19 on 2025-02-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_remove_book_published_date_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
