# Generated by Django 5.1.7 on 2025-04-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
